import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-apartment',
  templateUrl: './apartment.component.html',
  styleUrls: ['./apartment.component.scss']
})
export class ApartmentComponent implements OnInit {

  apartment = [
    ['ch-banner1.jpg','CITY GATE 2','CITY GATE 2 - Căn hộ chị Thảo','Chủ đầu tư: Ms. Thảo','Quy mô: 65 ms (2 phòng ngủ)','Mức đầu tư: 320 triệu','',
    'Không gian sống hiện đại và tinh tế thể hiện sự sáng tạo và tài năng của đội ngũ kiến trúc sư New Construction. Sự kết hợp hài hòa giữa phong cách hiện đại với những sản phẩm nội thất gỗ chất lượng, mang tới một không gian sống hoàn hảo và lý tưởng hơn bao giờ hết'],
    ['ch-banner2.jpg','Feliz En Vista','Feliz En Vista - Căn hộ anh Ngọc Minh','Chủ đầu tư: Anh Ngọc Minh','Quy mô: 100m2 - 2 Phòng Ngủ','Ngân sách: 725 triệu','Phong cách: Hiện đại - Đơn giản',
    'Căn hộ Duplex với diện tích 100m2 tại chung Feliz En Vista - Quận 2 được thiết kế theo phong cách Hiện đại - Đơn giản. Phần lớn nội thất sử dụng chủ yếu từ chất liệu gỗ với thiết kế tối giản, cùng sự hợp lý trong cách bố trí làm thêm phần sang trọng, tinh tế cho không gian. Màu gỗ chủ đạo kết hợp với tone màu xám, tạo nên không gian vô cùng ấm cúng.'],
    ['ch-banner3.jpg','Hà Đô Centrosa Garden','Hà Đô Centrosa Garden - Căn hộ chị Hải','Chủ đầu tư: Chị Hải','Quy mô: 60m2 - 2 Phòng ngủ','Ngân sách: 200 triệu','',
    'Với căn hộ 2 phòng ngủ gói gọn trong diện tích 60m2, New Construction tạo nên không gian sống lý tưởng với đầy đủ tiện nghi. Đồng thời đạt được sự hài lòng của gia chủ về phong cách thiết kế Hiện đại. Nội thất căn hộ sử dụng hầu hết từ chất liệu gỗ công nghiệp, được thiết kế đơn giản mà vẫn mang nét sang trọng, tinh tế. Tone màu chủ đạo là màu trắng kết hợp với màu gỗ làm sáng không gian và tạo cảm giác không gian rộng hơn.'],
    ['ch-banner4.jpg','Hà Đô Centrosa Garden','Hà Đô Centrosa Garden - Căn hộ anh Tùng','Chủ đầu tư: Anh Tùng','Quy mô: 65 m2 - 2 Phòng ngủ','Ngân sách: 355 triệu','',
    'Căn hộ 2 phòng ngủ có phong cách hiện đại với tone màu trắng làm chủ đạo, điểm nhấn là các món nội thất màu xanh ngọc, tạo nên không gian sống trẻ trung và năng động. Căn hộ với các món nội thất được thiết kế đơn giản nhưng vẫn đáp ứng đầy đủ tiện nghi và công năng, đồng thời với sự sắp xếp bố trí hợp lý tạo nét đẹp thẩm mỹ cho không gian.'],
    ['ch-banner5.jpg','Hà Đô Centrosa Garden','Hà Đô Centrosa Garden - Căn hộ anh Phát','Chủ đầu tư: Anh Phát','Quy mô: 65 m2 - 2 Phòng ngủ','Ngân sách: 245 triệu','',
    'Không gian căn hộ 65m2 đầy ấm cúng được New Construction thiết kế theo phong cách hiện đại, trẻ trung, phù hợp với đôi vợ chồng trẻ. Nội thất được cân nhắc lựa chọn kỹ về mẫu mã và chất liệu để vừa phù hợp không gian, vừa cân đối được ngân sách của gia chủ nhưng vẫn đảm bảo được tính thẩm mỹ cho căn hộ.'],
    ['ch-banner6.jpg','Hà Đô Centrosa Garden','Hà Đô Centrosa Garden - Căn hộ anh Vương','Chủ Đầu Tư: Anh Vương','Quy mô: 130m2 - 3 Phòng ngủ','Ngân sách: 1tỷ2','Phong cách: Tân Cổ Điển',
    'Căn hộ rộng 120m2 với 3 phòng ngủ được thiết kế theo phong cách Tân Cổ Điển theo ý tưởng của Chủ Đầu Tư. Căn hộ nổi bậc bởi các món nội thất cao cấp, cùng lối kiến trúc độc đáo tạo nên không gian sống sang trọng, thể hiện đẳng cấp của gia chủ.'],
    ['ch-banner7.jpg','Hà Đô Centrosa Garden','Hà Đô Centrosa Garden - Căn hộ chú Minh','Chủ Đầu Tư: Chú Minh','Quy mô: 65m2','Ngân sách: 320 triệu','Phong cách: Hiện đại',
    'Được thiết kế theo phong cách hiện đại với tone màu xám nhiều cấp độ làm chủ đạo, căn hộ 65m2 toát lên vẻ đẹp sang trọng và tinh tế. Tuy vậy, gia chủ vẫn dành cho con mình một phòng riêng với thiết kế trẻ trung và màu sắc tươi tắn, khắc biệt với thiết kế tổng thể căn hộ.'],
    ['ch-banner8.jpg','Hà Đô Centrosa Garden','Hà Đô Centrosa Garden - Căn hộ anh Hùng','Chủ Đầu Tư: Anh Hùng','Quy mô: 70m2 - 3 Phòng Ngủ','Ngân sách: 350 triệu','Phong cách: Hiện đại',
    'Với vẻ đẹp nhẹ nhàng và tinh tế, căn hộ rộng 70m2 được đội ngũ New Construction thiết kế theo phong cách hiện đại với lấy màu trắng và màu gỗ làm chủ đạo, tạo nên không gian vô cùng ấm cúng. Căn hộ cung cấp đầy đủ công năng với 3 phòng ngủ (2 phòng ngủ lớn và 1 phòng ngủ nhỏ) và khu vực lô gia thoáng mát.'],
    ['ch-banner9.jpg','Hà Đô Centrosa Garden','Hà Đô Centrosa Garden - Căn hộ anh Tuấn','Chủ Đầu Tư: Anh Tuấn','Quy mô: 65m2 - 1 Phòng Ngủ','Ngân sách: 300 triệu','Phong cách: Hiện đại',
    'Chủ đầu tư chọn tone màu xám làm chủ đạo cho thiết kế căn hộ với diện tích 70m2. Màu xám được sử dụng khéo léo với nhiều cấp độ khác nhau tạo cảm giác không gian ấm cúng và sang trọng.'],
    ['ch-banner10.jpg','Saigon Pearl','Saigon Pearl - Căn hộ anh Hiển','Chủ Đầu Tư: Anh Hiển','Quy mô: 65m2 - 2 Phòng Ngủ','Ngân sách: 335 triệu','Phong cách: Retro',
    'Chủ đầu tư vô cùng ấn tượng và hài lòng với thiết kế của New Construction, với đề bài là phong cách Retro đơn giản, màu sắc trẻ trung. Sử dụng và kết hợp một cách khéo léo các màu sắc tươi tắn, cùng gam màu đèn vàng, nội thất gỗ; tổng thể tạo một không gian ấm cúng và tươi trẻ.'],
    ['ch-banner11.jpg','Mizuki Park','Mizuki Park - Căn hộ chị Vi','Chủ Đầu Tư: Chị Vi','Quy mô: 65m2 - 2 Phòng Ngủ','Ngân sách: 335 triệu','',
    'Phong cách tối giản Nhật với hầu hết chất liệu được sử dụng là từ gỗ, New Construction đã thiết kế nên căn hộ mang đến sự hài lòng tuyệt đối từ chủ đầu tư ngay lần gửi phương án đầu tiên.'],
    ['ch-banner12.jpg','Vinhomes Grand Park','Vinhomes Grand Park - Căn hộ Anh Đệ','Chủ Đầu Tư: Anh Đệ','Quy mô: 65m2 - 2 Phòng Ngủ','Ngân sách: 300 triệu','Phong cách: Hiện đại','Căn hộ 65m2 với 2 phòng ngủ được thiết kế theo phong cách hiện đại lấy tone màu trắng - xám làm chủ đạo, tạo nên không gian sống sang trọng và vô cùng tinh tế.'],
    ['ch-banner13.jpg','Carillon 7','Carillon 7 - Căn hộ chị Thoa','Chủ Đầu Tư: Chị Thoa','Quy mô: 50m2 - 1 Phòng Ngủ','Ngân sách: 225 triệu','',
    'Mẫu thiết kế đơn giản cho căn hộ chỉ 50m2 nhưng vẫn mang nét hiện đại. Điểm nổi bậc trong thiết kế là sự bày trí và kết hợp một cách hợp lý các món nội thất trong không gian, tạo vẻ đẹp hài hòa và đồng bộ.'],
    ['ch-banner14.jpg','Carillon 7 - Tân Phú','Carillon 7 - Tân Phú - Căn hộ anh Hoài','Chủ Đầu Tư: Anh Hoài','Quy mô: 65m2 - 2 Phòng Ngủ','Ngân sách: 385 triệu','Phong cách: Hiện đại - Sang trọng',
    'Thiết kế mang phong cách hiện đại, sang trọng được New Construction thể hiện dựa trên những yêu cầu từ Chủ Đầu Tư. Đây là kết quả của việc không ngừng sáng tạo từ đội ngũ thiết kế để mang đến một không gian sống thoải mái và mang tính thẩm mỹ cao nhất trong căn hộ 65m2 này.'],
    ['ch-banner15.jpg','City Gate 2','City Gate 2 - Căn hộ chị Linh','Chủ Đầu Tư: Chị Linh','Quy mô: 70m2 - 3 Phòng Ngủ','Ngân sách: 320 triệu','',
    'Căn hộ rộng 70m3 với 3 phòng ngủ được thiết kế theo phong cách hiện đại được đội ngũ thiết kế New Construction cân nhắc giữ lại nét đẹp kiến trúc vốn có của căn hộ, đồng thời không ngừng sáng tạo để tạo nên không gian mới hài hòa và mang tính cá nhân hóa cao nhất.'],
    ['ch-banner16.jpg','City Gate 2','City Gate 2 - Căn hộ anh Thành','Chủ Đầu Tư: Anh Thành','Quy mô: 50 m2 - 1 Phòng Ngủ','Ngân sách: 300 triệu','',
    'Căn hộ hoàn thiện với đa phần sử dụng chất liệu gỗ cho các món nội thất, màu gỗ hài hòa với màu trắng tạo nên không gian sống ấm cúng. Căn hộ hoàn thiện với đa phần sử dụng chất liệu gỗ cho các món nội thất, màu gỗ hài hòa với màu trắng tạo nên không gian sống ấm cúng.'],
    ['ch-banner17.jpg','Hà Đô Centrosa Garden','Hà Đô Centrosa Garden - Căn hộ Chị Yến','Chủ Đầu Tư: Chị Yến','Quy mô: 60m2 - 2 Phòng Ngủ','Ngân sách: 110 triệu','',
    'Gian bếp được xem là linh hồn của Nội Thất Căn Hộ. Về mặt thẩm mỹ, một căn bếp hiện đại sẽ làm không gian căn hộ thêm phần sang trọng; ngoài ra, căn bếp với công năng được bố trí hợp lý sẽ tạo thuận lợi cho Gia Chủ khi sử dụng,…Đó cũng là những yêu cầu cơ bản từ Chủ Đầu Tư khi thiết kế gian bếp này.'],
    ['ch-banner18.jpg','City Gate 2','City Gate 2 - Căn hộ Anh Đạt','Chủ Đầu Tư: Anh Đạt','Quy mô: 65m2 (2 phòng ngủ)','Ngân sách: 320 triệu','',
    'Phong cách hiện đại luôn tạo ấn tượng bởi sự phóng khoáng, trẻ trung và sáng tạo vượt mọi khuôn khổ. Với diện tích 65m2, căn hộ Gate 2 được thiết kế theo phong cách hiện đại nhằm tôn lên cá tính của gia chủ. Không gian nổi bật với các gam mù tươi sáng, kết hợp với những mảng màu ấm nóng, tạo nên một bức tranh nghệ thuật đầy chiều sâu.'],
    ['ch-banner19.jpg','Carillon 7','Carillon 7 - Căn hộ anh Sơn','Chủ Đầu Tư: Anh Sơn','Quy mô: 65m2 (2 phòng ngủ)','Ngân sách: 500 triệu','',
    'Không gian sống sang trọng đẳng cấp được thể hiện qua thiết kế căn hộ 65m2 tại chung cư SaiGon Asiana. Căn hộ sang trọng, hiện đại nhưng cũng không làm mất đi vẻ ấm cúng là yêu cầu từ Chủ Đầu Tư cho phong cách thiết kế.'],
    ['ch-banner20.jpg','City Gate 2','City Gate 2 - Căn hộ chị Hương','Chủ Đầu Tư: Chị Hương','Quy mô: 65m2 (2 phòng ngủ)','Ngân sách: 300 triệu','',
    'Lấy tone màu trắng làm tone màu chủ đạo cho thiết kế căn hộ 65m2. Căn hộ hoàn thiện mang sự sang trọng và tinh tế đặc biệt, tone màu trắng góp phần lớn trong việc cải thiện diện tích và làm cho không gian có cảm giác cao rộng hơn.'],
    ['ch-banner21.jpg','Green River','Green River - Căn hộ anh Trình','Chủ Đầu Tư: Anh Trình','Quy mô: 65m2 (2 phòng ngủ)','Ngân sách: 300 triệu','',
    'Căn hộ với thiết kế sang trọng, trầm ấm, sử dụng nội thất cao cấp càng thể hiện đẳng cấp của gia chủ. Tuy vậy, gia chủ vẫn dành cho con mình một phòng riêng với thiết kế trẻ trung và màu sắc tươi tắn, khắc biệt với thiết kế tổng thể căn hộ.'],
    ['ch-banner22.jpg','Hà Đô Centrosa Garden','Hà Đô Centrosa Garden - Căn hộ chị Thanh','Chủ Đầu Tư: Chị Thanh','Quy mô: 65m2 (2 phòng ngủ)','Ngân sách: 600 triệu','',
    'Thiết kế căn hộ Tân Cổ Điển với tone màu trắng tinh tế, không làm gợi nên cảm giác quá phô trương; thiết kế vừa phải nhưng thể hiện đẳng cấp, sang trọng của Gia Chủ.'],
    ['ch-banner23.jpg','Hà Đô Centrosa Garden','Hà Đô Centrosa Garden - Căn hộ cô Thùy','Chủ Đầu Tư: Cô Thùy','Quy mô: 65m2 (2 Phòng ngủ)','Ngân sách: 350 triệu','',
    'Được thiết kế theo phong cách hiện đại với tone màu xám nhiều cấp độ làm chủ đạo, căn hộ 65m2 toát lên vẻ đẹp sang trọng và tinh tế.'],
    ['ch-banner24.jpg','Sunshine Garden','Sunshine Garden - Căn hộ anh Trí','Chủ Đầu Tư: Anh Trí','Quy mô: 75m2','Ngân sách: 700 triệu','',''],
  ];
  apartmentimg = [
    [
      ['chct1.jpg'],
      ['chct2.jpg'],
      ['chct3.jpg'],
      ['chct4.jpg'],
      ['chct5.jpg'],
      ['chct6.jpg'],
      ['chct7.jpg'],
      ['chct8.jpg'],
    ],
    [
      ['nm1.jpg'],
      ['nm2.jpg'],
      ['nm3.jpg'],
      ['nm4.jpg'],
      ['nm5.jpg'],
      ['nm6.jpg'],
      ['nm7.jpg'],
      ['nm8.jpg'],
    ],
    [
      ['ch1.jpg'],
      ['ch2.jpg'],
      ['ch3.jpg'],
      ['ch4.jpg'],
      ['ch5.jpg'],
      ['ch6.jpg'],
      ['ch7.jpg'],
      ['ch8.jpg'],
      ['ch9.jpg'],
      ['ch10.jpg'],
      ['ch11.jpg'],
      ['ch12.jpg'],
    ],
    [
      ['at1.jpg'],
      ['at2.jpg'],
      ['at3.jpg'],
      ['at4.jpg'],
      ['at5.jpg'],
      ['at6.jpg'],
      ['at7.jpg'],
      ['at8.jpg'],
      ['at9.jpg'],
      ['at10.jpg'],
      ['at11.jpg'],
    ],
    [
      ['ap1.jpg'],
      ['ap2.jpg'],
      ['ap3.jpg'],
      ['ap4.jpg'],
      ['ap5.jpg'],
      ['ap6.jpg'],
      ['ap7.jpg'],
      ['ap8.jpg'],
      ['ap9.jpg'],
    ],
    [
      ['av1.jpg'],
      ['av2.jpg'],
      ['av3.jpg'],
      ['av4.jpg'],
      ['av5.jpg'],
      ['av6.jpg'],
      ['av7.jpg'],
      ['av8.jpg'],
      ['av9.jpg'],
      ['av10.jpg'],
      ['av11.jpg'],
      ['av12.jpg'],
      ['av13.jpg'],
      ['av14.jpg'],
      ['av15.jpg'],
      ['av16.jpg'],
      ['av17.jpg'],
      ['av18.jpg'],
      ['av19.jpg'],
      ['av20.jpg'],
      ['av21.jpg'],
      ['av22.jpg'],
      ['av23.jpg'],
      ['av24.jpg'],
      ['av25.jpg'],
      ['av26.jpg'],
      ['av27.jpg'],
      ['av28.jpg'],
      ['av29.jpg'],
      ['av30.jpg'],
    ],
    [
      ['cm1.jpg'],
      ['cm2.jpg'],
      ['cm3.jpg'],
      ['cm4.jpg'],
      ['cm5.jpg'],
      ['cm6.jpg'],
      ['cm7.jpg'],
      ['cm8.jpg'],
      ['cm9.jpg'],
      ['cm10.jpg'],
    ],
    [
      ['ah1.jpg'],
      ['ah2.jpg'],
      ['ah3.jpg'],
      ['ah4.jpg'],
      ['ah5.jpg'],
      ['ah6.jpg'],
      ['ah7.jpg'],
      ['ah8.jpg'],
      ['ah9.jpg'],
      ['ah10.jpg'],
      ['ah11.jpg'],
      ['ah12.jpg'],
      ['ah13.jpg'],
      ['ah14.jpg'],
    ],
    [
      ['chat1.jpg'],
      ['chat2.jpg'],
      ['chat3.jpg'],
      ['chat4.jpg'],
      ['chat5.jpg'],
      ['chat6.jpg'],
      ['chat7.jpg'],
      ['chat8.jpg'],
    ],
    [
      ['ahien1.jpg'],
      ['ahien2.jpg'],
      ['ahien3.jpg'],
      ['ahien4.jpg'],
      ['ahien5.jpg'],
      ['ahien6.jpg'],
      ['ahien7.jpg'],
    ],
    [
      ['cv1.jpg'],
      ['cv2.jpg'],
      ['cv3.jpg'],
      ['cv4.jpg'],
      ['cv5.jpg'],
      ['cv6.jpg'],
      ['cv7.jpg'],
      ['cv8.jpg'],
      ['cv9.jpg'],
      ['cv10.jpg'],
      ['cv11.jpg'],
      ['cv12.jpg'],
    ],
    [
      ['ade1.jpg'],
      ['ade2.jpg'],
      ['ade3.jpg'],
      ['ade4.jpg'],
      ['ade5.jpg'],
      ['ade6.jpg'],
      ['ade7.jpg'],
      ['ade8.jpg'],
      ['ade9.jpg'],
    ],
    [
      ['ct1.jpg'],
      ['ct2.jpg'],
      ['ct3.jpg'],
      ['ct4.jpg'],
      ['ct5.jpg'],
      ['ct6.jpg'],
      ['ct7.jpg'],
      ['ct8.jpg'],
      ['ct9.jpg'],
    ],
    [
      ['ahoai1.jpg'],
      ['ahoai2.jpg'],
      ['ahoai3.jpg'],
      ['ahoai4.jpg'],
      ['ahoai5.jpg'],
      ['ahoai6.jpg'],
      ['ahoai7.jpg'],
      ['ahoai8.jpg'],
      ['ahoai9.jpg'],
    ],
    [
      ['clinh1.jpg'],
      ['clinh2.jpg'],
      ['clinh3.jpg'],
      ['clinh4.jpg'],
      ['clinh5.jpg'],
      ['clinh6.jpg'],
      ['clinh7.jpg'],
      ['clinh8.jpg'],
      ['clinh9.jpg'],
    ],
    [
      ['athanh1.jpg'],
      ['athanh2.jpg'],
      ['athanh3.jpg'],
      ['athanh4.jpg'],
      ['athanh5.jpg'],
      ['athanh6.jpg'],
    ],
    [
      ['cyen1.jpg'],
      ['cyen2.jpg'],
      ['cyen3.jpg'],
      ['cyen4.jpg'],
      ['cyen5.jpg'],
      ['cyen6.jpg'],
      ['cyen7.jpg'],
    ],
    [
      ['adat1.jpg'],
      ['adat2.jpg'],
      ['adat3.jpg'],
      ['adat4.jpg'],
      ['adat5.jpg'],
      ['adat6.jpg'],
      ['adat7.jpg'],
      ['adat8.jpg'],
      ['adat9.jpg'],
    ],
    [
      ['ason1.jpg'],
      ['ason2.jpg'],
      ['ason3.jpg'],
      ['ason4.jpg'],
      ['ason5.jpg'],
      ['ason6.jpg'],
      ['ason7.jpg'],
      ['ason8.jpg'],
      ['ason9.jpg'],
      ['ason10.jpg'],
      ['ason11.jpg'],
      ['ason12.jpg'],
    ],
    [
      ['chuong1.jpg'],
      ['chuong2.jpg'],
      ['chuong3.jpg'],
      ['chuong4.jpg'],
      ['chuong5.jpg'],
      ['chuong6.jpg'],
      ['chuong7.jpg'],
    ],
    [
      ['atrinh1.jpg'],
      ['atrinh2.jpg'],
      ['atrinh3.jpg'],
      ['atrinh4.jpg'],
      ['atrinh5.jpg'],
      ['atrinh6.jpg'],
      ['atrinh7.jpg'],
      ['atrinh8.jpg'],
      ['atrinh9.jpg'],
    ],
    [
      ['cthanh1.jpg'],
      ['cthanh2.jpg'],
      ['cthanh3.jpg'],
      ['cthanh4.jpg'],
      ['cthanh5.jpg'],
      ['cthanh6.jpg'],
      ['cthanh7.jpg'],
      ['cthanh8.jpg'],
      ['cthanh9.jpg'],
    ],
    [
      ['cthuy1.jpg'],
      ['cthuy2.jpg'],
      ['cthuy3.jpg'],
      ['cthuy4.jpg'],
      ['cthuy5.jpg'],
      ['cthuy6.jpg'],
      ['cthuy7.jpg'],
      ['cthuy8.jpg'],
      ['cthuy9.jpg'],
      ['cthuy10.jpg'],
      ['cthuy11.jpg'],
      ['cthuy12.jpg'],
    ],
    [
      ['atri1.jpg'],
      ['atri2.jpg'],
      ['atri3.jpg'],
      ['atri4.jpg'],
      ['atri5.jpg'],
    ],
  ];

  constructor() { }

  ngOnInit(): void {
  }

}
